[package]
name = "starlight_format"
version = "0.1.0"
edition = "2021"


[dependencies]
diesel = { version = "2.2", features = ["postgres", "sqlite"] }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }